### ISSUE TITLE
Finite State Machines and Ember

### ISSUE THREAD

**Issue by abhilashlr** [emberjs-chennai/talks#10]

**Comment by sankar-ganesh** [comment]
@abhilashlr Did you receive any nomination before on this item? Shall I take this up? Let's sync up in office today!

**Comment by abhilashlr** [comment]
> @abhilashlr Did you receive any nomination before on this item? Shall I take this up? Let's sync up in office today!

Sure @sankar-ganesh you are most welcome to pick this up. I will assign it to you.

**Comment by sankar-ganesh** [comment]
@abhilashlr Please find the presentation attached [here](https://docs.google.com/presentation/d/1D2ac6E_faggsfxUa6CZBpMy6_NlQ1GlDaS1QTbydAwM/edit?usp=sharing)

**Comment by gokatz** [comment]
Talk video: https://www.youtube.com/watch?v=0lFNUybdWJs&list=PLh_rF0Qob_sxjhg9qPTlXn-6EZzmmTHoc&index=6
